export interface kanaType {
  hiragana: string
  katakana: string
  romaji: string
}

export interface KanjiType {
  kanji: string
  strokes: number
  grade: number
  freq: number
  jlpt_new: number
  meanings: string[]
  onyomi: string[]
  kunyomi: string[]
  wk_level: number
  wk_meanings: string[]
  wk_onyomi: string[]
  wk_kunyomi: string[]
  wk_radicals: string[]
}

export const initialKanjiValue = {
  kanji: '',
  strokes: 1,
  grade: 1,
  freq: 2,
  jlpt_new: 5,
  meanings: [''],
  onyomi: [''],
  kunyomi: [''],
  wk_level: 1,
  wk_meanings: [''],
  wk_onyomi: [''],
  wk_kunyomi: [''],
  wk_radicals: [''],
}

export const kanjiData = [
  {
    kanji: '一',
    strokes: 1,
    grade: 1,
    freq: 2,
    jlpt_new: 5,
    meanings: ['One', 'One Radical (no.1)'],
    onyomi: ['いち', 'いつ'],
    kunyomi: ['ひと-', 'ひと.つ'],
    wk_level: 1,
    wk_meanings: ['One'],
    wk_onyomi: ['いち', 'いつ'],
    wk_kunyomi: ['!ひと'],
    wk_radicals: ['Ground'],
  },
  {
    kanji: '二',
    strokes: 2,
    grade: 1,
    freq: 9,
    jlpt_new: 5,
    meanings: ['Two', 'Two Radical (no. 7)'],
    onyomi: ['に', 'じ'],
    kunyomi: ['ふた', 'ふた.つ', 'ふたたび'],
    wk_level: 1,
    wk_meanings: ['Two'],
    wk_onyomi: ['に'],
    wk_kunyomi: ['!ふた'],
    wk_radicals: ['Two'],
  },
  {
    kanji: '九',
    strokes: 2,
    grade: 1,
    freq: 55,
    jlpt_new: 5,
    meanings: ['Nine'],
    onyomi: ['きゅう', 'く'],
    kunyomi: ['ここの', 'ここの.つ'],
    wk_level: 1,
    wk_meanings: ['Nine'],
    wk_onyomi: ['く', 'きゅう'],
    wk_kunyomi: ['!ここの'],
    wk_radicals: ['Nine'],
  },
  {
    kanji: '七',
    strokes: 2,
    grade: 1,
    freq: 115,
    jlpt_new: 5,
    meanings: ['Seven'],
    onyomi: ['しち'],
    kunyomi: ['なな', 'なな.つ', 'なの'],
    wk_level: 1,
    wk_meanings: ['Seven'],
    wk_onyomi: ['しち'],
    wk_kunyomi: ['!なな', '!なの'],
    wk_radicals: ['Seven'],
  },
  {
    kanji: '人',
    strokes: 2,
    grade: 1,
    freq: 5,
    jlpt_new: 5,
    meanings: ['Person'],
    onyomi: ['じん', 'にん'],
    kunyomi: ['ひと', '-り', '-と'],
    wk_level: 1,
    wk_meanings: ['Person'],
    wk_onyomi: ['にん', 'じん'],
    wk_kunyomi: ['!ひと', '!と'],
    wk_radicals: ['Person'],
  },
  {
    kanji: '入',
    strokes: 2,
    grade: 1,
    freq: 56,
    jlpt_new: 5,
    meanings: ['Enter', 'Insert'],
    onyomi: ['にゅう', 'じゅ'],
    kunyomi: ['い.る', '-い.る', '-い.り', 'い.れる', '-い.れ', 'はい.る'],
    wk_level: 1,
    wk_meanings: ['Enter'],
    wk_onyomi: ['にゅう'],
    wk_kunyomi: ['!はい', '!い'],
    wk_radicals: ['Enter'],
  },
  {
    kanji: '八',
    strokes: 2,
    grade: 1,
    freq: 92,
    jlpt_new: 5,
    meanings: ['Eight', 'Eight Radical (no. 12)'],
    onyomi: ['はち'],
    kunyomi: ['や', 'や.つ', 'やっ.つ', 'よう'],
    wk_level: 1,
    wk_meanings: ['Eight'],
    wk_onyomi: ['はち'],
    wk_kunyomi: ['!や', '!よう'],
    wk_radicals: ['Fins'],
  },
  {
    kanji: '十',
    strokes: 2,
    grade: 1,
    freq: 8,
    jlpt_new: 5,
    meanings: ['Ten'],
    onyomi: ['じゅう', 'じっ', 'じゅっ'],
    kunyomi: ['とお', 'と'],
    wk_level: 1,
    wk_meanings: ['Ten'],
    wk_onyomi: ['じゅう'],
    wk_kunyomi: ['!とお'],
    wk_radicals: ['Cross'],
  },
  {
    kanji: '三',
    strokes: 3,
    grade: 1,
    freq: 14,
    jlpt_new: 5,
    meanings: ['Three'],
    onyomi: ['さん', 'ぞう'],
    kunyomi: ['み', 'み.つ', 'みっ.つ'],
    wk_level: 1,
    wk_meanings: ['Three'],
    wk_onyomi: ['さん'],
    wk_kunyomi: ['!み'],
    wk_radicals: ['Ground', 'Two'],
  },
  {
    kanji: '上',
    strokes: 3,
    grade: 1,
    freq: 35,
    jlpt_new: 5,
    meanings: ['Above', 'Up'],
    onyomi: ['じょう', 'しょう', 'しゃん'],
    kunyomi: [
      'うえ',
      '-うえ',
      'うわ-',
      'かみ',
      'あ.げる',
      '-あ.げる',
      'あ.がる',
      '-あ.がる',
      'あ.がり',
      '-あ.がり',
      'のぼ.る',
      'のぼ.り',
      'のぼ.せる',
      'のぼ.す',
      'たてまつ.る',
    ],
    wk_level: 1,
    wk_meanings: ['Above', '^Up', '^Over'],
    wk_onyomi: ['じょう'],
    wk_kunyomi: ['!うえ', '!あ', '!のぼ', '!うわ', '!かみ'],
    wk_radicals: ['Toe', 'Ground'],
  },
  {
    kanji: '下',
    strokes: 3,
    grade: 1,
    freq: 97,
    jlpt_new: 5,
    meanings: ['Below', 'Down', 'Descend', 'Give', 'Low', 'Inferior'],
    onyomi: ['か', 'げ'],
    kunyomi: [
      'した',
      'しも',
      'もと',
      'さ.げる',
      'さ.がる',
      'くだ.る',
      'くだ.り',
      'くだ.す',
      '-くだ.す',
      'くだ.さる',
      'お.ろす',
      'お.りる',
    ],
    wk_level: 1,
    wk_meanings: ['Below', '^Down', '^Under', '^Beneath'],
    wk_onyomi: ['か', 'げ'],
    wk_kunyomi: ['!した', '!さ', '!くだ', '!お'],
    wk_radicals: ['Ground', 'Toe'],
  },
  {
    kanji: '大',
    strokes: 3,
    grade: 1,
    freq: 7,
    jlpt_new: 5,
    meanings: ['Large', 'Big'],
    onyomi: ['だい', 'たい'],
    kunyomi: ['おお-', 'おお.きい', '-おお.いに'],
    wk_level: 1,
    wk_meanings: ['Big', '^Large'],
    wk_onyomi: ['たい', 'だい'],
    wk_kunyomi: ['!おお'],
    wk_radicals: ['Big'],
  },
  {
    kanji: '女',
    strokes: 3,
    grade: 1,
    freq: 151,
    jlpt_new: 5,
    meanings: ['Woman', 'Female'],
    onyomi: ['じょ', 'にょ', 'にょう'],
    kunyomi: ['おんな', 'め'],
    wk_level: 1,
    wk_meanings: ['Woman'],
    wk_onyomi: ['じょ'],
    wk_kunyomi: ['!おんな', '!め'],
    wk_radicals: ['Woman'],
  },
  {
    kanji: '山',
    strokes: 3,
    grade: 1,
    freq: 131,
    jlpt_new: 5,
    meanings: ['Mountain'],
    onyomi: ['さん', 'せん'],
    kunyomi: ['やま'],
    wk_level: 1,
    wk_meanings: ['Mountain'],
    wk_onyomi: ['さん'],
    wk_kunyomi: ['!やま'],
    wk_radicals: ['Mountain'],
  },
  {
    kanji: '川',
    strokes: 3,
    grade: 1,
    freq: 181,
    jlpt_new: 5,
    meanings: [
      'Stream',
      'River',
      'River Or Three-stroke River Radical (no. 47)',
    ],
    onyomi: ['せん'],
    kunyomi: ['かわ'],
    wk_level: 1,
    wk_meanings: ['River'],
    wk_onyomi: ['!せん'],
    wk_kunyomi: ['かわ'],
    wk_radicals: ['River'],
  },
  {
    kanji: '土',
    strokes: 3,
    grade: 1,
    freq: 307,
    jlpt_new: 5,
    meanings: ['Soil', 'Earth', 'Ground', 'Turkey'],
    onyomi: ['ど', 'と'],
    kunyomi: ['つち'],
    wk_level: 2,
    wk_meanings: ['Dirt', '^Soil', '^Earth', '^Ground'],
    wk_onyomi: ['ど', '^と'],
    wk_kunyomi: ['!つち'],
    wk_radicals: ['Dirt'],
  },
  {
    kanji: '千',
    strokes: 3,
    grade: 1,
    freq: 195,
    jlpt_new: 5,
    meanings: ['Thousand'],
    onyomi: ['せん'],
    kunyomi: ['ち'],
    wk_level: 2,
    wk_meanings: ['Thousand'],
    wk_onyomi: ['せん'],
    wk_kunyomi: ['!ち'],
    wk_radicals: ['Thousand'],
  },
  {
    kanji: '子',
    strokes: 3,
    grade: 1,
    freq: 72,
    jlpt_new: 5,
    meanings: [
      'Child',
      'Sign Of The Rat',
      '11pm-1am',
      'First Sign Of Chinese Zodiac',
    ],
    onyomi: ['し', 'す', 'つ'],
    kunyomi: ['こ', '-こ', 'ね'],
    wk_level: 2,
    wk_meanings: ['Child', '^Kid'],
    wk_onyomi: ['し', 'す'],
    wk_kunyomi: ['!こ'],
    wk_radicals: ['Child'],
  },
  {
    kanji: '小',
    strokes: 3,
    grade: 1,
    freq: 114,
    jlpt_new: 5,
    meanings: ['Little', 'Small'],
    onyomi: ['しょう'],
    kunyomi: ['ちい.さい', 'こ-', 'お-', 'さ-'],
    wk_level: 2,
    wk_meanings: ['Small', '^Little'],
    wk_onyomi: ['しょう'],
    wk_kunyomi: ['!ちい', '!こ', '!お'],
    wk_radicals: ['Small'],
  },
  {
    kanji: '中',
    strokes: 4,
    grade: 1,
    freq: 11,
    jlpt_new: 5,
    meanings: ['In', 'Inside', 'Middle', 'Mean', 'Center'],
    onyomi: ['ちゅう'],
    kunyomi: ['なか', 'うち', 'あた.る'],
    wk_level: 2,
    wk_meanings: ['Middle', '^In', '^Inside', '^Center'],
    wk_onyomi: ['ちゅう'],
    wk_kunyomi: ['!なか'],
    wk_radicals: ['Middle'],
  },
  {
    kanji: '五',
    strokes: 4,
    grade: 1,
    freq: 31,
    jlpt_new: 5,
    meanings: ['Five'],
    onyomi: ['ご'],
    kunyomi: ['いつ', 'いつ.つ'],
    wk_level: 2,
    wk_meanings: ['Five'],
    wk_onyomi: ['ご'],
    wk_kunyomi: ['!いつ'],
    wk_radicals: ['Five'],
  },
  {
    kanji: '六',
    strokes: 4,
    grade: 1,
    freq: 93,
    jlpt_new: 5,
    meanings: ['Six'],
    onyomi: ['ろく', 'りく'],
    kunyomi: ['む', 'む.つ', 'むっ.つ', 'むい'],
    wk_level: 2,
    wk_meanings: ['Six'],
    wk_onyomi: ['ろく'],
    wk_kunyomi: ['!む'],
    wk_radicals: ['Lid', 'Fins'],
  },
  {
    kanji: '円',
    strokes: 4,
    grade: 1,
    freq: 69,
    jlpt_new: 5,
    meanings: ['Circle', 'Yen', 'Round'],
    onyomi: ['えん'],
    kunyomi: ['まる.い', 'まる', 'まど', 'まど.か', 'まろ.やか'],
    wk_level: 2,
    wk_meanings: ['Yen', '^Round', '^Circle'],
    wk_onyomi: ['えん'],
    wk_kunyomi: ['!まる'],
    wk_radicals: ['Lid', 'Head'],
  },
  {
    kanji: '天',
    strokes: 4,
    grade: 1,
    freq: 512,
    jlpt_new: 5,
    meanings: ['Heavens', 'Sky', 'Imperial'],
    onyomi: ['てん'],
    kunyomi: ['あまつ', 'あめ', 'あま-'],
    wk_level: 2,
    wk_meanings: ['Heaven'],
    wk_onyomi: ['てん'],
    wk_kunyomi: ['!あま'],
    wk_radicals: ['Heaven'],
  },
  {
    kanji: '日',
    strokes: 4,
    grade: 1,
    freq: 1,
    jlpt_new: 5,
    meanings: ['Day', 'Sun', 'Japan', 'Counter For Days'],
    onyomi: ['にち', 'じつ'],
    kunyomi: ['ひ', '-び', '-か'],
    wk_level: 2,
    wk_meanings: ['Sun', '^Day'],
    wk_onyomi: ['にち', 'じつ'],
    wk_kunyomi: ['!ひ', '!か', '!び'],
    wk_radicals: ['Sun'],
  },
  {
    kanji: '月',
    strokes: 4,
    grade: 1,
    freq: 23,
    jlpt_new: 5,
    meanings: ['Month', 'Moon'],
    onyomi: ['げつ', 'がつ'],
    kunyomi: ['つき'],
    wk_level: 2,
    wk_meanings: ['Moon', '^Month'],
    wk_onyomi: ['げつ', 'がつ'],
    wk_kunyomi: ['!つき'],
    wk_radicals: ['Moon'],
  },
  {
    kanji: '木',
    strokes: 4,
    grade: 1,
    freq: 317,
    jlpt_new: 5,
    meanings: ['Tree', 'Wood'],
    onyomi: ['ぼく', 'もく'],
    kunyomi: ['き', 'こ-'],
    wk_level: 2,
    wk_meanings: ['Tree', '^Wood'],
    wk_onyomi: ['もく', 'ぼく'],
    wk_kunyomi: ['!き', '!こ'],
    wk_radicals: ['Tree'],
  },
  {
    kanji: '水',
    strokes: 4,
    grade: 1,
    freq: 223,
    jlpt_new: 5,
    meanings: ['Water'],
    onyomi: ['すい'],
    kunyomi: ['みず', 'みず-'],
    wk_level: 2,
    wk_meanings: ['Water'],
    wk_onyomi: ['すい'],
    wk_kunyomi: ['!みず'],
    wk_radicals: ['Water'],
  },
  {
    kanji: '火',
    strokes: 4,
    grade: 1,
    freq: 574,
    jlpt_new: 5,
    meanings: ['Fire'],
    onyomi: ['か'],
    kunyomi: ['ひ', '-び', 'ほ-'],
    wk_level: 2,
    wk_meanings: ['Fire'],
    wk_onyomi: ['か'],
    wk_kunyomi: ['!ひ', '!ほ'],
    wk_radicals: ['Fire'],
  },
  {
    kanji: '出',
    strokes: 5,
    grade: 1,
    freq: 13,
    jlpt_new: 5,
    meanings: ['Exit', 'Leave', 'Go Out', 'Come Out', 'Put Out', 'Protrude'],
    onyomi: ['しゅつ', 'すい'],
    kunyomi: ['で.る', '-で', 'だ.す', '-だ.す', 'い.でる', 'い.だす'],
    wk_level: 2,
    wk_meanings: ['Exit'],
    wk_onyomi: ['しゅつ'],
    wk_kunyomi: ['!で', '!だ'],
    wk_radicals: ['Mountain'],
  },
  {
    kanji: '右',
    strokes: 5,
    grade: 1,
    freq: 602,
    jlpt_new: 5,
    meanings: ['Right'],
    onyomi: ['う', 'ゆう'],
    kunyomi: ['みぎ'],
    wk_level: 2,
    wk_meanings: ['Right'],
    wk_onyomi: ['^う', 'ゆう'],
    wk_kunyomi: ['!みぎ'],
    wk_radicals: ['Narwhal', 'Mouth'],
  },
  {
    kanji: '四',
    strokes: 5,
    grade: 1,
    freq: 47,
    jlpt_new: 5,
    meanings: ['Four'],
    onyomi: ['し'],
    kunyomi: ['よ', 'よ.つ', 'よっ.つ', 'よん'],
    wk_level: 2,
    wk_meanings: ['Four'],
    wk_onyomi: ['し'],
    wk_kunyomi: ['!よん', '!よ'],
    wk_radicals: ['Mouth', 'Legs'],
  },
  {
    kanji: '左',
    strokes: 5,
    grade: 1,
    freq: 630,
    jlpt_new: 5,
    meanings: ['Left'],
    onyomi: ['さ', 'しゃ'],
    kunyomi: ['ひだり'],
    wk_level: 2,
    wk_meanings: ['Left'],
    wk_onyomi: ['さ'],
    wk_kunyomi: ['!ひだり'],
    wk_radicals: ['Narwhal', 'Construction'],
  },
  {
    kanji: '本',
    strokes: 5,
    grade: 1,
    freq: 10,
    jlpt_new: 5,
    meanings: [
      'Book',
      'Present',
      'Main',
      'Origin',
      'True',
      'Real',
      'Counter For Long Cylindrical Things',
    ],
    onyomi: ['ほん'],
    kunyomi: ['もと'],
    wk_level: 2,
    wk_meanings: ['Book', '^Origin', '^Real', '^Main'],
    wk_onyomi: ['ほん'],
    wk_kunyomi: ['!もと'],
    wk_radicals: ['Book'],
  },
  {
    kanji: '白',
    strokes: 5,
    grade: 1,
    freq: 483,
    jlpt_new: 5,
    meanings: ['White'],
    onyomi: ['はく', 'びゃく'],
    kunyomi: ['しろ', 'しら-', 'しろ.い'],
    wk_level: 2,
    wk_meanings: ['White'],
    wk_onyomi: ['はく'],
    wk_kunyomi: ['!しろ', '!しら'],
    wk_radicals: ['White'],
  },
  {
    kanji: '万',
    strokes: 3,
    grade: 2,
    freq: 375,
    jlpt_new: 5,
    meanings: ['Ten Thousand', '10,000'],
    onyomi: ['まん', 'ばん'],
    kunyomi: ['よろず'],
    wk_level: 3,
    wk_meanings: ['Ten Thousand'],
    wk_onyomi: ['まん', 'ばん'],
    wk_kunyomi: [],
    wk_radicals: ['Leaf', 'Sword'],
  },
  {
    kanji: '今',
    strokes: 4,
    grade: 2,
    freq: 49,
    jlpt_new: 5,
    meanings: ['Now'],
    onyomi: ['こん', 'きん'],
    kunyomi: ['いま'],
    wk_level: 3,
    wk_meanings: ['Now'],
    wk_onyomi: ['こん'],
    wk_kunyomi: ['!いま'],
    wk_radicals: ['Now'],
  },
  {
    kanji: '午',
    strokes: 4,
    grade: 2,
    freq: 154,
    jlpt_new: 5,
    meanings: [
      'Noon',
      'Sign Of The Horse',
      '11am-1pm',
      'Seventh Sign Of Chinese Zodiac',
    ],
    onyomi: ['ご'],
    kunyomi: ['うま'],
    wk_level: 3,
    wk_meanings: ['Noon'],
    wk_onyomi: ['ご'],
    wk_kunyomi: [],
    wk_radicals: ['Slide', 'Dry'],
  },
  {
    kanji: '友',
    strokes: 4,
    grade: 2,
    freq: 622,
    jlpt_new: 5,
    meanings: ['Friend'],
    onyomi: ['ゆう'],
    kunyomi: ['とも'],
    wk_level: 3,
    wk_meanings: ['Friend'],
    wk_onyomi: ['ゆう'],
    wk_kunyomi: ['!とも'],
    wk_radicals: ['Narwhal', 'Stool'],
  },
  {
    kanji: '父',
    strokes: 4,
    grade: 2,
    freq: 646,
    jlpt_new: 5,
    meanings: ['Father'],
    onyomi: ['ふ'],
    kunyomi: ['ちち'],
    wk_level: 3,
    wk_meanings: ['Father', '^Dad'],
    wk_onyomi: ['!ふ'],
    wk_kunyomi: ['ちち'],
    wk_radicals: ['Father'],
  },
  {
    kanji: '北',
    strokes: 5,
    grade: 2,
    freq: 153,
    jlpt_new: 5,
    meanings: ['North'],
    onyomi: ['ほく'],
    kunyomi: ['きた'],
    wk_level: 3,
    wk_meanings: ['North'],
    wk_onyomi: ['ほく'],
    wk_kunyomi: ['!きた'],
    wk_radicals: ['Fingers', 'Spoon'],
  },
  {
    kanji: '半',
    strokes: 5,
    grade: 2,
    freq: 224,
    jlpt_new: 5,
    meanings: ['Half', 'Middle', 'Odd Number', 'Semi-', 'Part-'],
    onyomi: ['はん'],
    kunyomi: ['なか.ば'],
    wk_level: 3,
    wk_meanings: ['Half'],
    wk_onyomi: ['はん'],
    wk_kunyomi: ['!なか'],
    wk_radicals: ['Triceratops', 'Dry'],
  },
  {
    kanji: '外',
    strokes: 5,
    grade: 2,
    freq: 81,
    jlpt_new: 5,
    meanings: ['Outside'],
    onyomi: ['がい', 'げ'],
    kunyomi: ['そと', 'ほか', 'はず.す', 'はず.れる', 'と-'],
    wk_level: 3,
    wk_meanings: ['Outside'],
    wk_onyomi: ['がい'],
    wk_kunyomi: ['!そと', '!はず'],
    wk_radicals: ['Evening', 'Toe'],
  },
  {
    kanji: '母',
    strokes: 5,
    grade: 2,
    freq: 570,
    jlpt_new: 5,
    meanings: ['Mother'],
    onyomi: ['ぼ'],
    kunyomi: ['はは', 'も'],
    wk_level: 3,
    wk_meanings: ['Mother', '^Mom', '^Mum'],
    wk_onyomi: ['!ぼ'],
    wk_kunyomi: ['はは'],
    wk_radicals: ['Sun', 'Drop'],
  },
  {
    kanji: '生',
    strokes: 5,
    grade: 1,
    freq: 29,
    jlpt_new: 5,
    meanings: ['Life', 'Genuine', 'Birth'],
    onyomi: ['せい', 'しょう'],
    kunyomi: [
      'い.きる',
      'い.かす',
      'い.ける',
      'う.まれる',
      'うま.れる',
      'う.まれ',
      'うまれ',
      'う.む',
      'お.う',
      'は.える',
      'は.やす',
      'き',
      'なま',
      'なま-',
      'な.る',
      'な.す',
      'む.す',
      '-う',
    ],
    wk_level: 3,
    wk_meanings: ['Life'],
    wk_onyomi: ['せい', 'しょう'],
    wk_kunyomi: ['!い', '!なま', '!う', '!は', '!き'],
    wk_radicals: ['Life'],
  },
  {
    kanji: '休',
    strokes: 6,
    grade: 1,
    freq: 642,
    jlpt_new: 5,
    meanings: ['Rest', 'Day Off', 'Retire', 'Sleep'],
    onyomi: ['きゅう'],
    kunyomi: ['やす.む', 'やす.まる', 'やす.める'],
    wk_level: 4,
    wk_meanings: ['Rest'],
    wk_onyomi: ['きゅう'],
    wk_kunyomi: ['!やす'],
    wk_radicals: ['Leader', 'Tree'],
  },
  {
    kanji: '先',
    strokes: 6,
    grade: 1,
    freq: 173,
    jlpt_new: 5,
    meanings: ['Before', 'Ahead', 'Previous', 'Future', 'Precedence'],
    onyomi: ['せん'],
    kunyomi: ['さき', 'ま.ず'],
    wk_level: 4,
    wk_meanings: ['Previous', '^Ahead', '^Past', '^Former'],
    wk_onyomi: ['せん'],
    wk_kunyomi: ['!さき', '!まず'],
    wk_radicals: ['Slide', 'Dirt', 'Legs'],
  },
  {
    kanji: '名',
    strokes: 6,
    grade: 1,
    freq: 177,
    jlpt_new: 5,
    meanings: ['Name', 'Noted', 'Distinguished', 'Reputation'],
    onyomi: ['めい', 'みょう'],
    kunyomi: ['な', '-な'],
    wk_level: 4,
    wk_meanings: ['Name', '^Famous'],
    wk_onyomi: ['めい', 'みょう'],
    wk_kunyomi: ['!な'],
    wk_radicals: ['Evening', 'Mouth'],
  },
  {
    kanji: '年',
    strokes: 6,
    grade: 1,
    freq: 6,
    jlpt_new: 5,
    meanings: ['Year', 'Counter For Years'],
    onyomi: ['ねん'],
    kunyomi: ['とし'],
    wk_level: 4,
    wk_meanings: ['Year'],
    wk_onyomi: ['ねん'],
    wk_kunyomi: ['!とし'],
    wk_radicals: ['Gun', 'Cow'],
  },
  {
    kanji: '気',
    strokes: 6,
    grade: 1,
    freq: 113,
    jlpt_new: 5,
    meanings: ['Spirit', 'Mind', 'Air', 'Atmosphere', 'Mood'],
    onyomi: ['き', 'け'],
    kunyomi: ['いき'],
    wk_level: 4,
    wk_meanings: ['Energy', '^Spirit'],
    wk_onyomi: ['き', 'け'],
    wk_kunyomi: ['!いき'],
    wk_radicals: ['Energy', 'Treasure'],
  },
  {
    kanji: '百',
    strokes: 6,
    grade: 1,
    freq: 163,
    jlpt_new: 5,
    meanings: ['Hundred'],
    onyomi: ['ひゃく', 'びゃく'],
    kunyomi: ['もも'],
    wk_level: 4,
    wk_meanings: ['Hundred'],
    wk_onyomi: ['ひゃく'],
    wk_kunyomi: ['!もも'],
    wk_radicals: ['Leaf', 'Sun'],
  },
  {
    kanji: '男',
    strokes: 7,
    grade: 1,
    freq: 240,
    jlpt_new: 5,
    meanings: ['Male'],
    onyomi: ['だん', 'なん'],
    kunyomi: ['おとこ', 'お'],
    wk_level: 4,
    wk_meanings: ['Man'],
    wk_onyomi: ['だん'],
    wk_kunyomi: ['!おとこ'],
    wk_radicals: ['Rice Paddy', 'Power'],
  },
  {
    kanji: '見',
    strokes: 7,
    grade: 1,
    freq: 22,
    jlpt_new: 5,
    meanings: [
      'See',
      'Hopes',
      'Chances',
      'Idea',
      'Opinion',
      'Look At',
      'Visible',
    ],
    onyomi: ['けん'],
    kunyomi: ['み.る', 'み.える', 'み.せる'],
    wk_level: 4,
    wk_meanings: ['See'],
    wk_onyomi: ['!けん'],
    wk_kunyomi: ['み'],
    wk_radicals: ['See'],
  },
  {
    kanji: '車',
    strokes: 7,
    grade: 1,
    freq: 333,
    jlpt_new: 5,
    meanings: ['Car'],
    onyomi: ['しゃ'],
    kunyomi: ['くるま'],
    wk_level: 4,
    wk_meanings: ['Car'],
    wk_onyomi: ['しゃ'],
    wk_kunyomi: ['!くるま'],
    wk_radicals: ['Car'],
  },
  {
    kanji: '毎',
    strokes: 6,
    grade: 2,
    freq: 436,
    jlpt_new: 5,
    meanings: ['Every'],
    onyomi: ['まい'],
    kunyomi: ['ごと', '-ごと.に'],
    wk_level: 5,
    wk_meanings: ['Every'],
    wk_onyomi: ['まい'],
    wk_kunyomi: ['!ごと'],
    wk_radicals: ['Gun', 'Window'],
  },
  {
    kanji: '行',
    strokes: 6,
    grade: 2,
    freq: 20,
    jlpt_new: 5,
    meanings: [
      'Going',
      'Journey',
      'Carry Out',
      'Conduct',
      'Act',
      'Line',
      'Row',
      'Bank',
    ],
    onyomi: ['こう', 'ぎょう', 'あん'],
    kunyomi: [
      'い.く',
      'ゆ.く',
      '-ゆ.き',
      '-ゆき',
      '-い.き',
      '-いき',
      'おこな.う',
      'おこ.なう',
    ],
    wk_level: 5,
    wk_meanings: ['Go'],
    wk_onyomi: ['こう', 'ぎょう'],
    wk_kunyomi: ['!い', '!おこな', '!ゆ'],
    wk_radicals: ['Go'],
  },
  {
    kanji: '西',
    strokes: 6,
    grade: 2,
    freq: 259,
    jlpt_new: 5,
    meanings: ['West', 'Spain'],
    onyomi: ['せい', 'さい', 'す'],
    kunyomi: ['にし'],
    wk_level: 5,
    wk_meanings: ['West'],
    wk_onyomi: ['せい', 'さい'],
    wk_kunyomi: ['!にし'],
    wk_radicals: ['West'],
  },
  {
    kanji: '何',
    strokes: 7,
    grade: 2,
    freq: 340,
    jlpt_new: 5,
    meanings: ['What'],
    onyomi: ['か'],
    kunyomi: ['なに', 'なん', 'なに-', 'なん-'],
    wk_level: 5,
    wk_meanings: ['What'],
    wk_onyomi: ['!か'],
    wk_kunyomi: ['なに', 'なん'],
    wk_radicals: ['Leader', 'Lip Ring'],
  },
  {
    kanji: '来',
    strokes: 7,
    grade: 2,
    freq: 102,
    jlpt_new: 5,
    meanings: ['Come', 'Due', 'Next', 'Cause', 'Become'],
    onyomi: ['らい', 'たい'],
    kunyomi: ['く.る', 'きた.る', 'きた.す', 'き.たす', 'き.たる', 'き', 'こ'],
    wk_level: 5,
    wk_meanings: ['Come', '^Next'],
    wk_onyomi: ['らい'],
    wk_kunyomi: ['!く'],
    wk_radicals: ['Ground', 'Rice'],
  },
  {
    kanji: '学',
    strokes: 8,
    grade: 1,
    freq: 63,
    jlpt_new: 5,
    meanings: ['Study', 'Learning', 'Science'],
    onyomi: ['がく'],
    kunyomi: ['まな.ぶ'],
    wk_level: 5,
    wk_meanings: ['Study', '^Learn', '^Learning'],
    wk_onyomi: ['がく'],
    wk_kunyomi: ['!まな'],
    wk_radicals: ['Viking', 'Child'],
  },
  {
    kanji: '金',
    strokes: 8,
    grade: 1,
    freq: 53,
    jlpt_new: 5,
    meanings: ['Gold'],
    onyomi: ['きん', 'こん', 'ごん'],
    kunyomi: ['かね', 'かな-', '-がね'],
    wk_level: 5,
    wk_meanings: ['Gold'],
    wk_onyomi: ['きん'],
    wk_kunyomi: ['!かね'],
    wk_radicals: ['Gold'],
  },
  {
    kanji: '雨',
    strokes: 8,
    grade: 1,
    freq: 950,
    jlpt_new: 5,
    meanings: ['Rain'],
    onyomi: ['う'],
    kunyomi: ['あめ', 'あま-', '-さめ'],
    wk_level: 5,
    wk_meanings: ['Rain'],
    wk_onyomi: ['!う'],
    wk_kunyomi: ['あめ', 'あま'],
    wk_radicals: ['Rain'],
  },
  {
    kanji: '国',
    strokes: 8,
    grade: 2,
    freq: 3,
    jlpt_new: 5,
    meanings: ['Country'],
    onyomi: ['こく'],
    kunyomi: ['くに'],
    wk_level: 6,
    wk_meanings: ['Country'],
    wk_onyomi: ['こく'],
    wk_kunyomi: ['!くに'],
    wk_radicals: ['Mouth', 'King', 'Drop'],
  },
  {
    kanji: '東',
    strokes: 8,
    grade: 2,
    freq: 37,
    jlpt_new: 5,
    meanings: ['East'],
    onyomi: ['とう'],
    kunyomi: ['ひがし'],
    wk_level: 6,
    wk_meanings: ['East'],
    wk_onyomi: ['とう'],
    wk_kunyomi: ['!ひがし'],
    wk_radicals: ['Tree', 'Sun'],
  },
  {
    kanji: '長',
    strokes: 8,
    grade: 2,
    freq: 12,
    jlpt_new: 5,
    meanings: ['Long', 'Leader', 'Superior', 'Senior'],
    onyomi: ['ちょう'],
    kunyomi: ['なが.い', 'おさ'],
    wk_level: 6,
    wk_meanings: ['Long', '^Leader'],
    wk_onyomi: ['ちょう'],
    wk_kunyomi: ['!なが'],
    wk_radicals: ['Long'],
  },
  {
    kanji: '前',
    strokes: 9,
    grade: 2,
    freq: 27,
    jlpt_new: 5,
    meanings: ['In Front', 'Before'],
    onyomi: ['ぜん'],
    kunyomi: ['まえ', '-まえ'],
    wk_level: 6,
    wk_meanings: ['Front', '^Before'],
    wk_onyomi: ['ぜん'],
    wk_kunyomi: ['!まえ'],
    wk_radicals: ['Horns', 'Ground', 'Moon', 'Knife'],
  },
  {
    kanji: '南',
    strokes: 9,
    grade: 2,
    freq: 341,
    jlpt_new: 5,
    meanings: ['South'],
    onyomi: ['なん', 'な'],
    kunyomi: ['みなみ'],
    wk_level: 6,
    wk_meanings: ['South'],
    wk_onyomi: ['なん'],
    wk_kunyomi: ['!みなみ'],
    wk_radicals: ['Cross', 'Head', 'Horns', 'Dry'],
  },
  {
    kanji: '後',
    strokes: 9,
    grade: 2,
    freq: 26,
    jlpt_new: 5,
    meanings: ['Behind', 'Back', 'Later'],
    onyomi: ['ご', 'こう'],
    kunyomi: ['のち', 'うし.ろ', 'うしろ', 'あと', 'おく.れる'],
    wk_level: 6,
    wk_meanings: ['Behind', '^After', '^Back', '^Rear'],
    wk_onyomi: ['ご', 'こう'],
    wk_kunyomi: ['!うし', '!あと', '!のち'],
    wk_radicals: ['Loiter', 'Poop', 'Winter'],
  },
  {
    kanji: '食',
    strokes: 9,
    grade: 2,
    freq: 328,
    jlpt_new: 5,
    meanings: ['Eat', 'Food'],
    onyomi: ['しょく', 'じき'],
    kunyomi: ['く.う', 'く.らう', 'た.べる', 'は.む'],
    wk_level: 6,
    wk_meanings: ['Eat', '^Meal'],
    wk_onyomi: ['しょく'],
    wk_kunyomi: ['!た', '!く'],
    wk_radicals: ['Eat'],
  },
  {
    kanji: '校',
    strokes: 10,
    grade: 1,
    freq: 294,
    jlpt_new: 5,
    meanings: ['Exam', 'School', 'Printing', 'Proof', 'Correction'],
    onyomi: ['こう', 'きょう'],
    kunyomi: [],
    wk_level: 7,
    wk_meanings: ['School'],
    wk_onyomi: ['こう'],
    wk_kunyomi: [],
    wk_radicals: ['Tree', 'Lid', 'Father'],
  },
  {
    kanji: '時',
    strokes: 10,
    grade: 2,
    freq: 16,
    jlpt_new: 5,
    meanings: ['Time', 'Hour'],
    onyomi: ['じ'],
    kunyomi: ['とき', '-どき'],
    wk_level: 7,
    wk_meanings: ['Time', "^O'clock", '^Hour'],
    wk_onyomi: ['じ'],
    wk_kunyomi: ['!とき'],
    wk_radicals: ['Sun', 'Temple'],
  },
  {
    kanji: '高',
    strokes: 10,
    grade: 2,
    freq: 65,
    jlpt_new: 5,
    meanings: ['Tall', 'High', 'Expensive'],
    onyomi: ['こう'],
    kunyomi: ['たか.い', 'たか', '-だか', 'たか.まる', 'たか.める'],
    wk_level: 7,
    wk_meanings: ['Tall', '^Expensive', '^High'],
    wk_onyomi: ['こう'],
    wk_kunyomi: ['!たか'],
    wk_radicals: ['Lid', 'Mouth', 'Mustache'],
  },
  {
    kanji: '間',
    strokes: 12,
    grade: 2,
    freq: 33,
    jlpt_new: 5,
    meanings: ['Interval', 'Space'],
    onyomi: ['かん', 'けん'],
    kunyomi: ['あいだ', 'ま', 'あい'],
    wk_level: 8,
    wk_meanings: ['Interval', '^Interval Of Time', '^Time Interval'],
    wk_onyomi: ['かん', '^けん'],
    wk_kunyomi: ['!あいだ', '!ま'],
    wk_radicals: ['Gate', 'Sun'],
  },
  {
    kanji: '話',
    strokes: 13,
    grade: 2,
    freq: 134,
    jlpt_new: 5,
    meanings: ['Tale', 'Talk'],
    onyomi: ['わ'],
    kunyomi: ['はな.す', 'はなし'],
    wk_level: 8,
    wk_meanings: ['Talk', '^Speak'],
    wk_onyomi: ['わ'],
    wk_kunyomi: ['!はな', '!はなし'],
    wk_radicals: ['Say', 'Tongue'],
  },
  {
    kanji: '電',
    strokes: 13,
    grade: 2,
    freq: 268,
    jlpt_new: 5,
    meanings: ['Electricity'],
    onyomi: ['でん'],
    kunyomi: [],
    wk_level: 8,
    wk_meanings: ['Electricity'],
    wk_onyomi: ['でん'],
    wk_kunyomi: [],
    wk_radicals: ['Rain', 'Rice Paddy', 'Umbrella'],
  },
  {
    kanji: '聞',
    strokes: 14,
    grade: 2,
    freq: 319,
    jlpt_new: 5,
    meanings: ['Hear', 'Ask', 'Listen'],
    onyomi: ['ぶん', 'もん'],
    kunyomi: ['き.く', 'き.こえる'],
    wk_level: 10,
    wk_meanings: ['Hear'],
    wk_onyomi: ['ぶん', 'もん'],
    wk_kunyomi: ['!き'],
    wk_radicals: ['Gate', 'Ear'],
  },
  {
    kanji: '語',
    strokes: 14,
    grade: 2,
    freq: 301,
    jlpt_new: 5,
    meanings: ['Word', 'Speech', 'Language'],
    onyomi: ['ご'],
    kunyomi: ['かた.る', 'かた.らう'],
    wk_level: 10,
    wk_meanings: ['Language'],
    wk_onyomi: ['ご'],
    wk_kunyomi: ['!かた'],
    wk_radicals: ['Say', 'Five', 'Mouth'],
  },
  {
    kanji: '読',
    strokes: 14,
    grade: 2,
    freq: 618,
    jlpt_new: 5,
    meanings: ['Read'],
    onyomi: ['どく', 'とく', 'とう'],
    kunyomi: ['よ.む', '-よ.み'],
    wk_level: 10,
    wk_meanings: ['Read'],
    wk_onyomi: ['!とう', '!どく'],
    wk_kunyomi: ['よ'],
    wk_radicals: ['Say', 'Sell'],
  },
  {
    kanji: '書',
    strokes: 10,
    grade: 2,
    freq: 169,
    jlpt_new: 5,
    meanings: ['Write'],
    onyomi: ['しょ'],
    kunyomi: ['か.く', '-が.き', '-がき'],
    wk_level: 16,
    wk_meanings: ['Write', '^Writing'],
    wk_onyomi: ['しょ'],
    wk_kunyomi: ['!か'],
    wk_radicals: ['Brush', 'Sun'],
  },
]
